### ISSUE TITLE
pycuda.driver.CompileError

### ISSUE THREAD

**Issue by yichengggg** [mathiasunberath/DeepDRR#19]
Hi, 

I am trying to build the DeepDRR environment on my local Windows machine. I followed the instructions for installations, but when I am trying to run example_pojector.py, it seems to have issues with nvcc complier. The major error shows as:
 `pycuda.driver.CompileError: nvcc preprocessing of C:\Users\huyic\AppData\Local\Temp\tmpp4l1k4ir.cu failed
[command: nvcc --preprocess -arch sm_75 -m64 -ID:\Research\DeepDRR-master\cubic -Id:\anaconda\lib\site-packages\pycuda\cuda C:\Users\huyic\A`

I also traced to issue #13 and try to find something, but it seems like the temp.cu can be found under my machine but cannot compile. By the way, I am using **CUDA version 10.2 and PyTorch version 1.5.0**, I had no issues running default CUDA examples. 

I also attached the entire error message below. Hope to hear back from you!

Cheers :)

`
(base) D:\Research\DeepDRR-master>python example_projector.py
generating  6 matrices
projecting: air
D:\Research\DeepDRR-master\cubic
Traceback (most recent call last):
  File "example_projector.py", line 97, in <module>
    main()
  File "example_projector.py", line 93, in main
generate_projections_on_sphere(dicompath,save_path,min_theta,max_theta,min_phi,max_phi,spacing_theta,spacing_phi,photon_count,camera,spectrum,origin=origin,scatter=False)
  File "example_projector.py", line 40, in generate_projections_on_sphere
    forward_projections = projector.generate_projections(proj_mats, volume, materials, origin, voxel_size, camera.sensor_width, camera.sensor_height, mode="linear", max_blockind=200, threads=8)
  File "D:\Research\DeepDRR-master\projector.py", line 248, in generate_projections
    projector = ForwardProjector(density, materials[mat], voxel_size, origin=origin, mode = mode)
  File "D:\Research\DeepDRR-master\projector.py", line 12, in __init__
    self.mod = self.generateKernelModuleProjector()
  File "D:\Research\DeepDRR-master\projector.py", line 173, in generateKernelModuleProjector
    """, include_dirs=[bicubic_path], no_extern_c=True)
  File "D:\Anaconda\lib\site-packages\pycuda\compiler.py", line 291, in __init__
    arch, code, cache_dir, include_dirs)
  File "D:\Anaconda\lib\site-packages\pycuda\compiler.py", line 254, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "D:\Anaconda\lib\site-packages\pycuda\compiler.py", line 78, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "D:\Anaconda\lib\site-packages\pycuda\compiler.py", line 55, in preprocess_source
    cmdline, stderr=stderr)
pycuda.driver.CompileError: nvcc preprocessing of C:\Users\huyic\AppData\Local\Temp\tmpp4l1k4ir.cu failed
[command: nvcc --preprocess -arch sm_75 -m64 -ID:\Research\DeepDRR-master\cubic -Id:\anaconda\lib\site-packages\pycuda\cuda C:\Users\huyic\AppData\Local\Temp\tmpp4l1k4ir.cu --compiler-options -EP]`

**Comment by yichengggg** [comment]
Hi, 

It spent me few days to build the CUDA environment, and now I have successfully built required CUDA environment with PyCUDA on both **Windows** and **Linux Ubuntu 16.04**. Here I would like to put some recaps, to help anyone if needed.

### 1. Windows:
If you are new to **Windows** like me, and don't know how to add C compiler to path, this link below might be very helpful:
[https://code.visualstudio.com/docs/cpp/config-mingw](url)

### 2. Ubuntu 16.04
I strongly recommend to build DeepDRR required CUDA environment using NVIDIA's official installation guide:
[https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html](url)

It's suggested to follow the steps strictly, and not jumping between steps to avoid dependency errors. It's important to check that local driver(can be checked by `nvidia-smi`), and CUDA complier driver(can be checked by `nvcc --version`) are matched, and don't install additional driver if the machine already has one. Also,  **disable secure boot** when doing the installation. Here is an useful link to solve the local driver issue:
[https://askubuntu.com/questions/902636/nvidia-smi-command-not-found-ubuntu-16-04](url)

Sometimes, unfortunately, it might need to remove/reinstall CUDA toolkit to necessarily solve issues, it depends on how you installed CUDA toolkit on your machine, ways to remove CUDA toolkit on Ubuntu are different from using `runfile` or `deb` for installation. 

It's also very useful to read official installation guide section 7 to **verify installation**. Try to compile example provided by CUDA and running the binaries, this is often overlooked by the posts I went through online. 
[https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions](url)

Here are my specs to setup CUDA environment for DeepDRR:

**Python = 3.6.10
PyCuda = 2019.1.2
NVIDIA PyCuda = 2019.1.2
NVIDIAGPU = GTX1660
CUDA Toolkit = 10.1
Driver version = 430.64** 

As suggested in project README, DeepDRR works well with **CUDA 8.0**. And @gaocong13 suggested that it also worked with **CUDA 9.0**. So this time I have confirmed that  **CUDA 10.1** works. 

I think we can close this issue for now. @mathiasunberath please also feel free to share this to other users for reference. 

Cheers,
